/** Chapters 13–16 (PRD v0.3): decision separation and materiality, revision and withdrawal, complaints and appeals, competence and rotation. */
import { expect, test } from '@playwright/test'
import { enterAs, runRevision, statementCode, tickAll } from './helpers'

test('ch.13 — the warning needs an acknowledgement, Helena is refused the decision with the reason shown, Marc acknowledges and issues', async ({ page }) => {
  test.setTimeout(120_000)
  // Tomas (IR): the aggregation panel warns; approving needs the acknowledgement comment.
  await enterAs(page, /Tomas Lindqvist/)
  await page.goto('/engagements/svc_nw_pcf_2025/opinion')
  await expect(page.getByTestId('aggregation-panel').first()).toBeVisible()
  await expect(page.getByTestId('materiality-warning').first()).toBeVisible()
  await page.getByRole('button', { name: 'Independent review', exact: true }).click()
  const approve = page.getByRole('button', { name: 'Approve' })
  await expect(approve).toBeDisabled()
  await page.getByTestId('materiality-ack').fill('The understatement is corrected in the verified figure the opinion covers; unqualified remains appropriate on the verified value.')
  await tickAll(page)
  await approve.click()
  await expect(page.getByText('Iteration 1: manager review')).toBeVisible()

  // Helena edited a verified value: the decision control is disabled and the notice says why and who may decide.
  await enterAs(page, /Helena Brandt/)
  await page.goto('/engagements/svc_nw_pcf_2025/opinion')
  await expect(page.getByTestId('manager-decision')).toBeDisabled()
  const notice = page.getByTestId('eligibility-notice')
  await expect(notice).toBeVisible()
  await expect(notice).toContainText(/verified value/i)
  await expect(notice).toContainText('Marc Lefèvre')

  // Marc, outside the involved set, acknowledges, approves and issues; the statement carries the level and materiality.
  await enterAs(page, /Marc Lefèvre/)
  await page.goto('/engagements/svc_nw_pcf_2025/opinion')
  await page.getByTestId('manager-decision').click()
  await page.getByTestId('materiality-ack').fill('Acknowledged: the verified figure corrects the understatement; opinion unqualified on the verified value.')
  await tickAll(page)
  await page.getByRole('button', { name: 'Approve' }).click()
  await expect(page.getByText('Iteration 1: approved')).toBeVisible()
  await page.getByRole('button', { name: 'Issue opinion' }).first().click()
  await page.getByRole('button', { name: 'Issue opinion' }).last().click()
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'Opinion issued' })).toBeVisible({ timeout: 25_000 })
  await page.goto('/engagements/svc_nw_pcf_2025/opinion')
  await expect(page.getByTestId('statement-card').getByText('Limited assurance')).toBeVisible()
  await expect(page.getByTestId('statement-materiality')).toContainText(/Materiality 5 %/)
  await expect(page.getByTestId('statement-materiality')).toContainText(/warning acknowledged/)
  // The Service Log records the decision as taken outside the involved set (the UI disabled Helena's control, plan_v1 D30, so no refusal event was needed).
  await page.goto('/engagements/svc_nw_pcf_2025/log')
  await page.getByRole('combobox', { name: 'Filter by event type' }).selectOption('decisions')
  await expect(page.getByText(/approved by Marc Lefèvre \(outside the involved set\)/).first()).toBeVisible()
})

test('ch.14 — the withdrawn PCF 2024 page shows the banner; a revision re-runs COI, IR and decision and supersedes the old statement', async ({ page }) => {
  test.setTimeout(240_000)
  await enterAs(page, /Ingrid Vos/)
  const withdrawnCode = await statementCode(page, 'svc_nw_pcf_2024')
  await expect(page.getByTestId('statement-card').getByText('Statement withdrawn')).toBeVisible()
  await expect(page.getByText('Assurance withdrawn').first()).toBeVisible()
  await page.goto(`/verify/${withdrawnCode}`)
  await expect(page.getByText('This statement has been withdrawn')).toBeVisible()
  await expect(page.getByText('Error in the statement')).toBeVisible()
  await expect(page.getByText(/Figures and document hashes are not shown/)).toBeVisible()
  await expect(page.getByText('Genuine VERIFASSUR opinion')).toHaveCount(0)
  // The records that relied on it read "assurance withdrawn".
  await page.goto('/records/emission-factors')
  await expect(page.getByText(/factors? with assurance withdrawn/)).toBeVisible()
  // The seeded 2024 decarb revision: the old statement reads Superseded and links to the replacement.
  await page.goto('/engagements/svc_nw_decarb_2024/opinion')
  await expect(page.getByText('Statement history')).toBeVisible()
  const superseded = page.getByText('Superseded', { exact: true }).first()
  await expect(superseded).toBeVisible()

  // A live revision on the FY2024 inventory opinion: Helena opens, Marc decides, the chain runs again.
  await runRevision(page, 'svc_nw_inv_2024', 2)
  await enterAs(page, /Ingrid Vos/)
  const oldCode = (await page.goto('/engagements/svc_nw_inv_2024/opinion').then(async () => {
    await expect(page.getByText('Statement history')).toBeVisible()
    return (await page.locator('li:has-text("Superseded") code').first().innerText()).trim()
  }))
  await page.goto(`/verify/${oldCode}`)
  await expect(page.getByText('This statement has been superseded')).toBeVisible()
  await expect(page.getByRole('link', { name: /^VX-/ })).toBeVisible()
})

test('ch.15 — Ingrid follows her appeal, Priya is not offered as handler, Marc decides and closes it with the outcome recorded', async ({ page }) => {
  test.setTimeout(120_000)
  await enterAs(page, /Ingrid Vos/)
  await page.goto('/organisation?tab=cases')
  await page.getByTestId('case-case_nw_appeal_activity_data').click()
  const detail = page.getByTestId('case-detail')
  await expect(detail).toContainText('Marc Lefèvre')
  await expect(detail).toContainText('Under investigation')
  await expect(detail).not.toContainText('Priya (who rejected)')
  await page.getByRole('button', { name: 'Raise a complaint' }).click()
  await page.getByLabel(/^Subject/).fill('Too many notification e-mails')
  await page.getByLabel(/What happened/).fill('Three e-mails per finding is excessive.')
  await page.getByRole('button', { name: 'Submit complaint' }).click()
  await expect(page.getByText(/Complaint received/)).toBeVisible()

  // Helena may assign; Priya rejected the document and is excluded from the candidates.
  await enterAs(page, /Helena Brandt/)
  await page.goto('/staff/cases')
  await page.getByTestId('case-row-case_nw_appeal_activity_data').click()
  await page.getByRole('button', { name: /Reassign handler|Assign handler/ }).click()
  await expect(page.getByText(/Not offered \(involved set\): .*Priya Natarajan/)).toBeVisible()
  await expect(page.getByRole('combobox', { name: /Handler/ }).locator('option', { hasText: 'Priya Natarajan' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Cancel' }).last().click()

  // Marc, the handler, decides with a re-check action and closes.
  await enterAs(page, /Marc Lefèvre/)
  await page.goto('/staff/cases')
  await page.getByTestId('case-row-case_nw_appeal_activity_data').click()
  await page.getByRole('button', { name: 'Decide', exact: true }).click()
  await page.getByLabel(/Outcome summary/).fill('The invoices were in the pack filed by supplier. The rejection is lifted; the sample is re-checked as filed.')
  await page.getByLabel(/Reason \(audit log\)/).fill('Rejection reason was factually wrong; re-check ordered on the version as filed.')
  await page.getByRole('button', { name: 'Record decision' }).click()
  await expect(page.getByText(/Decided: upheld/)).toBeVisible()
  await page.getByRole('button', { name: 'Close case' }).click()
  await expect(page.getByText('Case closed.')).toBeVisible()

  await enterAs(page, /Ingrid Vos/)
  await page.goto('/organisation?tab=cases')
  await page.getByTestId('case-case_nw_appeal_activity_data').click()
  await expect(page.getByTestId('case-detail')).toContainText('Outcome: upheld')
})

test('ch.16 — a nomination warning needs a reason, the independent reviewer qualification is a hard block, a manager cannot edit their own profile', async ({ page }) => {
  test.setTimeout(120_000)
  await enterAs(page, /Helena Brandt/)
  await page.goto('/engagements/svc_atlas_decarb_2025/phases')
  await page.getByRole('button', { name: /Team nomination/ }).first().click()
  await expect(page.getByTestId('non-overridable')).toBeVisible()
  await expect(page.getByText('Rotation:').first()).toBeVisible()
  await page.getByRole('button', { name: 'Nominate', exact: true }).click()
  await page.getByRole('combobox', { name: 'Role for Jonas Weber' }).selectOption('verifier_technical_expert')
  const check = page.getByTestId('candidate-check')
  await expect(check).toBeVisible()
  await expect(check.getByLabel('Warning').first()).toBeVisible()
  const nominate = page.getByRole('dialog').getByRole('button', { name: 'Nominate', exact: true })
  await expect(nominate).toBeDisabled()
  await page.getByTestId('override-reason').fill('Jonas supports the volume reconciliation only; soil-carbon expertise is contracted externally.')
  await expect(nominate).toBeEnabled()
  // Helena holds no independent-reviewer qualification: a hard block that no reason lifts.
  await page.getByRole('combobox', { name: 'Role for Helena Brandt' }).selectOption('verifier_independent_reviewer')
  await expect(page.locator('[data-testid="candidate-check"][data-blocked="true"]')).toBeVisible()
  await expect(page.getByText('Blocked: no override lifts this rule')).toBeVisible()
  await expect(nominate).toBeDisabled()
  await page.getByRole('combobox', { name: 'Role for Helena Brandt' }).selectOption('')
  await expect(nominate).toBeEnabled()
  await nominate.click()
  await expect(page.getByText(/Team nominated/)).toBeVisible()
  await expect(page.getByRole('listitem').filter({ hasText: 'Jonas Weber' }).getByText('Warning overridden')).toBeVisible()

  // Own profile: the refusal is surfaced, not hidden.
  await page.goto('/staff/competence')
  await page.getByTestId('profile-usr_helena').click()
  await expect(page.getByText('This is your own profile')).toBeVisible()
  await page.getByTestId('add-qualification').click()
  await page.getByLabel('Valid from').fill('2026-01-01')
  await page.getByLabel('Valid until').fill('2029-01-01')
  await page.getByRole('button', { name: 'Add qualification', exact: true }).last().click()
  await expect(page.getByText(/cannot/i).last()).toBeVisible()
  // Another manager's profile can be edited; the Service Log on Atlas carries the override.
  await page.goto('/engagements/svc_atlas_decarb_2025/log')
  await page.getByRole('combobox', { name: 'Filter by event type' }).selectOption('team_checks')
  await expect(page.getByText(/Jonas Weber nominated as technical expert despite/).first()).toBeVisible()
})
